# Generated by Django 4.2.23 on 2025-06-27 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUpTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(max_length=255)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Follow-up"),
                            ("1_week", "1 Week Follow-up"),
                            ("2_week", "2 Week Follow-up"),
                            ("1_month", "1 Month Follow-up"),
                            ("thank_you", "Thank You After Interview"),
                            ("negotiation", "Negotiation Follow-up"),
                            ("custom", "Custom Template"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject_template", models.TextField()),
                ("body_template", models.TextField()),
                ("days_after_application", models.IntegerField(default=7)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "success_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("times_used", models.IntegerField(default=0)),
                ("responses_received", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FollowUpHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_date", models.DateTimeField(auto_now_add=True)),
                ("subject", models.CharField(max_length=500)),
                ("body", models.TextField()),
                ("response_received", models.BooleanField(default=False)),
                ("response_date", models.DateTimeField(blank=True, null=True)),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                            ("interview_invite", "Interview Invitation"),
                            ("rejection", "Rejection"),
                            ("no_response", "No Response"),
                        ],
                        default="no_response",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.jobapplication",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="followups.followuptemplate",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Follow-up histories",
                "ordering": ["-sent_date"],
            },
        ),
    ]
