# Generated by Django 4.2.23 on 2025-06-27 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_name", models.CharField(max_length=255)),
                ("job_categories", models.JSONField(default=list)),
                ("target_locations", models.JSONField(default=list)),
                (
                    "remote_preference",
                    models.CharField(default="remote", max_length=50),
                ),
                ("salary_min", models.IntegerField(blank=True, null=True)),
                ("salary_max", models.IntegerField(blank=True, null=True)),
                ("company_size_preference", models.JSONField(default=list)),
                ("auto_follow_up_enabled", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_search_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "config_name")},
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("job_url", models.URLField(blank=True, max_length=2000)),
                ("job_description", models.TextField(blank=True)),
                ("salary_range", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("remote_option", models.CharField(blank=True, max_length=50)),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("found", "Found"),
                            ("applied", "Applied"),
                            ("responded", "Responded"),
                            ("interview", "Interview Scheduled"),
                            ("offer", "Offer Received"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="found",
                        max_length=50,
                    ),
                ),
                ("applied_date", models.DateTimeField(blank=True, null=True)),
                ("last_follow_up_date", models.DateTimeField(blank=True, null=True)),
                ("follow_up_count", models.IntegerField(default=0)),
                ("next_follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_sequence_active", models.BooleanField(default=False)),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "interview_scheduled_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("offer_received", models.BooleanField(default=False)),
                ("offer_amount", models.IntegerField(blank=True, null=True)),
                ("rejection_received", models.BooleanField(default=False)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("company_rating", models.FloatField(blank=True, null=True)),
                ("glassdoor_rating", models.FloatField(blank=True, null=True)),
                ("match_percentage", models.IntegerField(blank=True, null=True)),
                ("documents_generated", models.BooleanField(default=False)),
                ("documents_folder_path", models.CharField(blank=True, max_length=500)),
                ("skills_match_analysis", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "search_config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobs.jobsearchconfig",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "application_status"],
                        name="jobs_jobapp_user_id_9d9322_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="jobs_jobapp_user_id_77eff9_idx",
                    ),
                    models.Index(
                        fields=["urgency_level"], name="jobs_jobapp_urgency_6dfa62_idx"
                    ),
                    models.Index(
                        fields=["next_follow_up_date"],
                        name="jobs_jobapp_next_fo_9f6bf7_idx",
                    ),
                ],
            },
        ),
    ]
