# Generated by Django 4.2.23 on 2025-06-27 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("follow_up", "Follow-up Due"),
                            ("job_found", "New Jobs Found"),
                            ("response_received", "Response Received"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("document_ready", "Documents Ready"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("action_url", models.URLField(blank=True)),
                ("action_text", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "related_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.jobapplication",
                    ),
                ),
                (
                    "related_search_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.jobsearchconfig",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light Theme"),
                            ("dark", "Dark Theme"),
                            ("auto", "Auto (System)"),
                        ],
                        default="light",
                        max_length=20,
                    ),
                ),
                (
                    "layout_density",
                    models.CharField(
                        choices=[
                            ("compact", "Compact"),
                            ("comfortable", "Comfortable"),
                            ("spacious", "Spacious"),
                        ],
                        default="comfortable",
                        max_length=20,
                    ),
                ),
                ("auto_refresh_enabled", models.BooleanField(default=True)),
                ("auto_refresh_interval", models.IntegerField(default=30)),
                ("show_welcome_message", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("browser_notifications", models.BooleanField(default=True)),
                ("follow_up_reminders", models.BooleanField(default=True)),
                ("job_alert_notifications", models.BooleanField(default=True)),
                ("default_widget_layout", models.JSONField(default=dict)),
                ("hidden_widgets", models.JSONField(default=list)),
                ("favorite_actions", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("stats_card", "Statistics Card"),
                            ("pipeline", "Application Pipeline"),
                            ("recent_activity", "Recent Activity"),
                            ("follow_ups", "Due Follow-ups"),
                            ("job_search", "Job Search Status"),
                            ("profile_completion", "Profile Completion"),
                            ("analytics_chart", "Analytics Chart"),
                            ("quick_actions", "Quick Actions"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=1)),
                ("height", models.IntegerField(default=1)),
                ("is_visible", models.BooleanField(default=True)),
                ("settings", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position_y", "position_x"],
                "unique_together": {("user", "widget_type")},
            },
        ),
        migrations.CreateModel(
            name="DashboardActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("search_created", "Search Configuration Created"),
                            ("search_executed", "Job Search Executed"),
                            (
                                "application_status_changed",
                                "Application Status Changed",
                            ),
                            ("follow_up_sent", "Follow-up Sent"),
                            ("document_generated", "Document Generated"),
                            ("document_downloaded", "Document Downloaded"),
                            ("profile_updated", "Profile Updated"),
                            ("dashboard_viewed", "Dashboard Viewed"),
                            ("widget_customized", "Widget Customized"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("metadata", models.JSONField(default=dict)),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "activity_type", "created_at"],
                        name="dashboard_d_user_id_0a6068_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="dashboard_d_created_87c030_idx"
                    ),
                ],
            },
        ),
    ]
