# Generated by Django 4.2.23 on 2025-06-27 19:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discord_user_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("linkedin_url", models.URLField(blank=True, max_length=500)),
                ("github_url", models.URLField(blank=True, max_length=500)),
                ("portfolio_url", models.URLField(blank=True, max_length=500)),
                (
                    "years_experience",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                ("education", models.TextField(blank=True)),
                ("current_job_title", models.CharField(blank=True, max_length=255)),
                ("current_company", models.CharField(blank=True, max_length=255)),
                ("key_skills", models.JSONField(blank=True, default=list)),
                ("preferred_salary_min", models.IntegerField(blank=True, null=True)),
                ("preferred_salary_max", models.IntegerField(blank=True, null=True)),
                (
                    "work_type_preference",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                            ("onsite", "On-site"),
                            ("flexible", "Flexible"),
                        ],
                        default="remote",
                        max_length=50,
                    ),
                ),
                ("preferred_company_sizes", models.JSONField(blank=True, default=list)),
                ("industries_of_interest", models.JSONField(blank=True, default=list)),
                (
                    "resume_file",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("profile_completion_percentage", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
