# Generated by Django 4.2.23 on 2025-06-27 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProviderStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                ("last_failure", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.IntegerField(default=0)),
                ("average_response_time", models.FloatField(default=0.0)),
                ("total_requests", models.IntegerField(default=0)),
                ("successful_requests", models.IntegerField(default=0)),
                (
                    "monthly_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("monthly_requests", models.IntegerField(default=0)),
                ("last_reset", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentGenerationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("ai_provider_used", models.CharField(default="groq", max_length=20)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
                ),
                ("documents_generated", models.IntegerField(default=0)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.jobapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyResearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_overview", models.TextField(blank=True)),
                ("recent_news", models.TextField(blank=True)),
                ("interview_talking_points", models.TextField(blank=True)),
                ("questions_to_ask", models.TextField(blank=True)),
                ("industry_context", models.TextField(blank=True)),
                ("research_date", models.DateTimeField(auto_now_add=True)),
                ("research_source", models.CharField(default="serper", max_length=20)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.jobapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("resume", "Resume"),
                            ("cover_letter", "Cover Letter"),
                            ("email_templates", "Email Templates"),
                            ("linkedin_messages", "LinkedIn Messages"),
                            ("video_script", "Video Pitch Script"),
                            ("company_research", "Company Research"),
                            ("followup_schedule", "Follow-up Schedule"),
                            ("skills_analysis", "Skills Analysis"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("content", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("file_size", models.IntegerField(default=0)),
                ("ai_provider", models.CharField(default="groq", max_length=20)),
                ("tokens_used", models.IntegerField(default=0)),
                ("generation_time", models.FloatField(default=0.0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.jobapplication",
                    ),
                ),
            ],
            options={
                "unique_together": {("application", "document_type")},
            },
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("groq", "Groq"), ("openrouter", "OpenRouter")],
                        max_length=20,
                    ),
                ),
                ("model_used", models.CharField(max_length=100)),
                ("tokens_used", models.IntegerField()),
                ("cost_usd", models.DecimalField(decimal_places=6, max_digits=10)),
                ("request_type", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="documents_a_user_id_086185_idx",
                    ),
                    models.Index(
                        fields=["provider", "created_at"],
                        name="documents_a_provide_442eb5_idx",
                    ),
                ],
            },
        ),
    ]
